FROM --platform=${TARGETPLATFORM} node:18

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

#
# install gcloud tools
#
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
     apt-transport-https \
     build-essential \
     ca-certificates \
     curl \
     cmake \
     git \
     git-crypt \
     gnupg \
     less \
     mandoc \
     openssl \
     openssh-server \
     python3 \
     python3-pip \
     python3-venv \     
     sudo \
     uuid-runtime \
     zip

#      openjdk-17-jdk \

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    xsltproc docbook docbook-xsl

RUN sed -i- -e 's/ALL=(ALL:ALL) ALL/ALL=(ALL:ALL) NOPASSWD:ALL/' /etc/sudoers
# RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN usermod -a -G sudo node
RUN mkdir -p /usr/local/share/.config
RUN chown -R node:node /usr/local/share/.config
RUN chown -R node:node /usr/local/bin

USER node
WORKDIR /home/node

RUN curl -s "https://get.sdkman.io" | bash && sudo mv /home/node/.sdkman /usr/local/share/.sdkman
RUN ln -s /usr/local/share/.sdkman /home/node/.sdkman
RUN echo 'if [ ! -f "${HOME}/.sdkman" ] ; then ln -s /usr/local/share/.sdkman "${HOME}/.sdkman" ; fi' >> /home/node/.bashrc
RUN echo '. "${HOME}/.sdkman/bin/sdkman-init.sh' >> /home/node/.bashrc
RUN bash -c ". /home/node/.sdkman/bin/sdkman-init.sh && sdk install java"
# RUN sdk install java 8-amzn
# RUN sdk install gradle
CMD bash
