/* Generated By:JavaCC: Do not edit this line. BshPPParserConstants.java */
package bpp;

public interface BshPPParserConstants {

  int EOF = 0;
  int PLAIN = 1;
  int PLAIN_DOLLAR = 2;
  int LPAREN = 3;
  int IDENTIFIER = 4;
  int LETTER = 5;
  int DIGIT = 6;
  int RPAREN = 7;
  int JLPAREN = 8;
  int JRPAREN = 9;
  int JPLAIN = 10;
  int JCHAR = 11;
  int JSTRING = 12;

  int DEFAULT = 0;
  int NOWHERE = 1;
  int JAVA = 2;

  String[] tokenImage = {
    "<EOF>",
    "<PLAIN>",
    "\"$$\"",
    "\"$(\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\")\"",
    "\"(\"",
    "\")\"",
    "<JPLAIN>",
    "<JCHAR>",
    "<JSTRING>",
  };

}
