/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bpp;

import org.junit.Test;

import com.google.common.io.ByteArrayDataInput;

import static org.junit.Assert.*;

import java.io.*;

public class BPPTest {
    @Test public void testHello() throws Exception {
        File inf = File.createTempFile("testHello", ".txt");
        PrintStream ps = new PrintStream(inf);
        ps.println("# who = \"World\"");
        ps.println("Hello, $(who)!");
        ps.flush();
        ps.close();
        File outf = File.createTempFile("testHello",".out");
        String[] args = {"-o",outf.getPath(),"-qq",inf.getPath()};
        BPP.main(args);
        BufferedReader br = new BufferedReader(new FileReader(outf));
        String expect = "Hello, World!";
        String result = br.readLine();
        assertEquals(expect, result);
        String expect2 = null;
        String result2 = br.readLine();
        assertEquals(expect2,result2);
    }
}
